version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - watcher

  watcher:
    build:
      context: ../../
      dockerfile: infra/docker/watcher.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ../env/watcher.env
      - ../env/watcherai.env
    environment:
      - NODE_ENV=production